sudo: required
dist: xenial
language: node_js
cache:
  directories:
    - ~/.npm
#    - ~/.docker-data
#before_cache:
#  - if [ "$TRAVIS_NODE_VERSION" = "12" ]; then .travis/docker-archive-cache.sh ; fi
node_js:
  - '12'
  - '10'
  - '8'
env:
  - DOCKER_DEVBOX_CA_CERTIFICATES="$TRAVIS_BUILD_DIR/.ca-certificates/GFI_Informatique*.pem"
before_install:
  #- if [ "$TRAVIS_NODE_VERSION" = "12" ]; then .travis/docker-unarchive-cache.sh; fi
  - if [ "$TRAVIS_NODE_VERSION" = "12" ]; then .travis/docker-install.sh; fi
  - if [ "$TRAVIS_NODE_VERSION" = "12" ]; then .travis/docker-devbox-install.sh; fi
before_script:
  - npm run lint
  - npm run build
script:
  - npm run test:prod
  - if [ "$TRAVIS_NODE_VERSION" = "12" ]; then npm run test:docker; fi
